name: Deploy Cloud Run job

on:
  push:
    branches:
      - master

env:
  JOB_NAME: bgg-scraping
  REGION: asia-northeast1
  PROJECT_ID: green-carrier-297111
  JOB_SERVICE_ACCOUNT: bgg-scraping@green-carrier-297111.iam.gserviceaccount.com
  SPREADSHEET_ID: 1DWXWf_8N1CbkxA6ezYcETIczQLg_vge3sHsPuHEApRQ

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: |
          npm run build

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Deploy Cloud Run job
        run: |
          ls -al
          cat .gcloudignore
          gcloud run jobs deploy ${{ env.JOB_NAME }} \
            --source . \
            --region ${{ env.REGION }} \
            --service-account ${{ env.JOB_SERVICE_ACCOUNT }} \
            --command node \
            --args dist/job.js \
            --memory 1GiB \
            --tasks 1 \
            --max-retries 1 \
            --task-timeout 1800s \
            --set-env-vars SPREADSHEET_ID=${{ env.SPREADSHEET_ID }},DATA_SHEET_NAME=data,METADATA_SHEET_NAME=metadata,MIN_ITEM_COUNT=450 \
            --quiet
